# Generated by Django 3.1.2 on 2020-10-04 23:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_auto_20201004_2328')
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Название специализации', max_length=64, validators=[django.core.validators.MaxLengthValidator], verbose_name='Название')),
                ('slug_title', models.SlugField(max_length=128, verbose_name='Слуг')),
            ],
            options={
                'verbose_name': 'Область работы',
                'verbose_name_plural': 'Области работ',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('short_description', models.CharField(help_text='Короткое и внятное описание кого вы ищете (макс. 128 символов)', max_length=128, validators=[django.core.validators.MaxLengthValidator], verbose_name='Короткое описание')),
                ('slug_short_description', models.SlugField(max_length=256, verbose_name='Слуг')),
                ('long_description', models.TextField(help_text='Подробно составленное объявление работает лучше, перечислите карьерные возмонжости, миссию вашей компании, инженерную культуру компании, etc', max_length=1024, validators=[django.core.validators.MaxLengthValidator], verbose_name='Полное описание вакансии')),
                ('level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('cto', 'CTO')], default='junior', max_length=16, verbose_name='Уровень кандидата')),
                ('salary_from', models.PositiveIntegerField(help_text='Уровень зарплаты от', verbose_name='Зарплата от')),
                ('salary_to', models.PositiveIntegerField(help_text='Уровень зарплаты до', verbose_name='Зарплата до')),
                ('company_name', models.CharField(help_text='Названик компании', max_length=256, validators=[django.core.validators.MaxLengthValidator], verbose_name='Название компании')),
                ('country', models.CharField(blank=True, help_text='Страна', max_length=32, validators=[django.core.validators.MaxLengthValidator], verbose_name='Страна')),
                ('city', models.CharField(blank=True, help_text='Город', max_length=128, validators=[django.core.validators.MaxLengthValidator], verbose_name='Город')),
                ('telegram', models.CharField(blank=True, help_text='Обратная свзяь в телеграм', max_length=128, validators=[django.core.validators.MaxLengthValidator], verbose_name='Телеграм')),
                ('email', models.EmailField(help_text='Электронная почта для обратной связи', max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='email')),
                ('scope', models.ForeignKey(help_text='Облать работы или тип конкретной специализации кандидата', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.scope', verbose_name='Область работы')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('-created_at',),
            },
        ),
    ]
