# Generated by Django 3.1.7 on 2021-03-17 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "title",
                    models.CharField(
                        help_text="Название специализации",
                        max_length=64,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Название",
                    ),
                ),
                ("slug_title", models.SlugField(max_length=128, verbose_name="Слуг")),
            ],
            options={
                "verbose_name": "Область работы",
                "verbose_name_plural": "Области работ",
                "ordering": ("-created_at",),
            },
        ),
    ]
