# Generated by Django 3.1.7 on 2021-03-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION pg_trgm;"),
        migrations.RunSQL("CREATE INDEX trgm_idx ON jobs_advert USING GIST (long_description gist_trgm_ops);"),
    ]
