# Generated by Django 3.1.7 on 2021-03-17 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stack",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Название")),
                ("slug_name", models.SlugField(max_length=128, verbose_name="Слуг")),
            ],
            options={
                "verbose_name": "Таг",
                "verbose_name_plural": "Таги",
            },
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="Короткое и внятное описание кого вы ищете (макс. 128 символов)",
                        max_length=128,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Короткое описание",
                    ),
                ),
                ("slug_short_description", models.SlugField(max_length=256, verbose_name="Слуг")),
                (
                    "long_description",
                    models.TextField(
                        help_text="Подробно составленное объявление работает лучше, перечислите карьерные возмонжости, миссию вашей компании, инженерную культуру компании, etc",
                        max_length=8192,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Полное описание вакансии",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("intern", "Intern"),
                            ("junior", "Junior"),
                            ("middle", "Middle"),
                            ("senior", "Senior"),
                            ("cto", "CTO"),
                        ],
                        default="junior",
                        max_length=16,
                        verbose_name="Уровень кандидата",
                    ),
                ),
                (
                    "salary_from",
                    models.PositiveIntegerField(help_text="Уровень зарплаты от", verbose_name="Зарплата от"),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, help_text="Уровень зарплаты до", null=True, verbose_name="Зарплата до"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("usd", "$"), ("eur", "€"), ("gbp", "£"), ("cny", "¥"), ("rub", "₽"), ("uah", "₴")],
                        default="usd",
                        max_length=16,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Названик компании",
                        max_length=256,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Страна",
                        max_length=128,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Город",
                        max_length=128,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Город",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="Обратная свзяь в телеграм",
                        max_length=128,
                        validators=[django.core.validators.MaxLengthValidator],
                        verbose_name="Телеграм",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Электронная почта для обратной связи",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator],
                        verbose_name="email",
                    ),
                ),
                ("is_moderate", models.BooleanField(default=False, verbose_name="Модерация")),
                (
                    "vacancy_source_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                        verbose_name="URL вакансии",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="Облать работы или тип конкретной специализации кандидата",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.scope",
                        verbose_name="Область работы",
                    ),
                ),
                (
                    "stack",
                    models.ManyToManyField(related_name="stack", to="jobs.Stack", verbose_name="Стэк технологий"),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ("-created_at",),
            },
        ),
    ]
