# Generated by Django 3.1.2 on 2020-10-19 21:56

from django.db import migrations, models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('jobs', '0002_advert_is_moderate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ('-created_at',), 'verbose_name': 'Область работы', 'verbose_name_plural': 'Области работ'},
        ),
        migrations.AddField(
            model_name='advert',
            name='stack',
            field=taggit.managers.TaggableManager(help_text='Разделяемый запятой запрашиваемый стэк технологий', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Технологический стэк'),
        ),
        migrations.AddField(
            model_name='advert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, help_text='Уровень зарплаты до', verbose_name='Зарплата до'),
        ),
    ]
