# Generated by Django 3.1.7 on 2021-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_advert_stack"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stack",
            options={"verbose_name": "Cтек технологий", "verbose_name_plural": "Cтек технологий"},
        ),
        migrations.AlterField(
            model_name="advert",
            name="stack",
            field=models.ManyToManyField(related_name="adverts", to="jobs.Stack", verbose_name="Стэк технологий"),
        ),
    ]
