# Generated by Django 3.1.2 on 2020-11-01 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201019_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='country',
            field=models.CharField(blank=True, help_text='Страна', max_length=128, validators=[django.core.validators.MaxLengthValidator], verbose_name='Страна'),
        ),
    ]
