# Generated by Django 3.1.2 on 2020-11-25 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_enlarge_country_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='country',
            field=models.CharField(blank=True, help_text='Страна', max_length=128, null=True, validators=[django.core.validators.MaxLengthValidator], verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, help_text='Уровень зарплаты до', null=True, verbose_name='Зарплата до'),
        ),
    ]
