# Generated by Django 3.1.2 on 2020-12-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_added_null_true_to_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='currency',
            field=models.CharField(choices=[('usd', '$'), ('eur', '€'), ('gbp', '£'), ('cny', '¥'), ('rub', '₽'), ('uah', '₴')], default='usd', max_length=16, verbose_name='Валюта'),
        ),
    ]
