# Generated by Django 3.1.2 on 2021-01-27 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_added_currency_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='vacancy_source_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator], verbose_name='URL вакансии'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта для обратной связи', max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='long_description',
            field=models.TextField(help_text='Подробно составленное объявление работает лучше, перечислите карьерные возмонжости, миссию вашей компании, инженерную культуру компании, etc', max_length=8192, validators=[django.core.validators.MaxLengthValidator], verbose_name='Полное описание вакансии'),
        ),
    ]
