version: '3'

services:
  postgres:
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    networks:
      - database_network

  redis:
    restart: always
    image: redis
    volumes:
      - ./rd_data:/data
    networks:
      - redis_network

  api:
    restart: always
    build: .
    command: /app/.ci/remoteme-entrypoint.sh
    environment:
      - DEBUG=False
      - SECRET_KEY=secret
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - REDIS=redis
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    volumes:
      - ./static_data:/app/static
    networks:
      - database_network
      - redis_network
      - nginx_network

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static_data:/static
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - nginx_network

volumes:
  pg_data:
  rd_data:
  static_data:

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  redis_network:
    driver: bridge