# Generated by Django 3.1.2 on 2020-10-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(choices=[('MAX_VIP_ADVERTS', 'Максимальное колличество VIP объявлений'), ('MAX_PIN_ADVERTS', 'Максимальное колличество PIN объявлений'), ('MAX_SIDEBAR_COMMENTS', 'Максимально колличество коментариев в сайдбаре'), ('ADVERTS_PER_PAGE', 'Колличество объявлений на странице'), ('BLOG_POST_PER_PAGE', 'Колличество постов блога на странице')], default='MAX_VIP_ADVERTS', max_length=128, unique=True, verbose_name='Ключ'),
        ),
    ]
